from .variure import VariureDeleteTestCase
from .variure import VariureUpdateTestCase
from .variure import VariureDetailTestCase
from .variure import VariureCreateTestCase
from .variure import VariureListTestCase
from .utilisateur import UtilisateurDeleteTestCase
from .utilisateur import UtilisateurUpdateTestCase
from .utilisateur import UtilisateurDetailTestCase
from .utilisateur import UtilisateurCreateTestCase
from .utilisateur import UtilisateurListTestCase
from .type_exemplaire import TypeExemplaireDeleteTestCase
from .type_exemplaire import TypeExemplaireUpdateTestCase
from .type_exemplaire import TypeExemplaireDetailTestCase
from .type_exemplaire import TypeExemplaireCreateTestCase
from .type_exemplaire import TypeExemplaireListTestCase
from .salle import SalleDeleteTestCase
from .salle import SalleUpdateTestCase
from .salle import SalleDetailTestCase
from .salle import SalleCreateTestCase
from .salle import SalleListTestCase
from .roles import RolesDeleteTestCase
from .roles import RolesUpdateTestCase
from .roles import RolesDetailTestCase
from .roles import RolesCreateTestCase
from .roles import RolesListTestCase
from .pouvoir import PouvoirDeleteTestCase
from .pouvoir import PouvoirUpdateTestCase
from .pouvoir import PouvoirDetailTestCase
from .pouvoir import PouvoirCreateTestCase
from .pouvoir import PouvoirListTestCase
from .posseseur_de_c_lef import PosseseurDeCLefDeleteTestCase
from .posseseur_de_c_lef import PosseseurDeCLefUpdateTestCase
from .posseseur_de_c_lef import PosseseurDeCLefDetailTestCase
from .posseseur_de_c_lef import PosseseurDeCLefCreateTestCase
from .posseseur_de_c_lef import PosseseurDeCLefListTestCase
from .porte import PorteDeleteTestCase
from .porte import PorteUpdateTestCase
from .porte import PorteDetailTestCase
from .porte import PorteCreateTestCase
from .porte import PorteListTestCase
from .personne import PersonneDeleteTestCase
from .personne import PersonneUpdateTestCase
from .personne import PersonneDetailTestCase
from .personne import PersonneCreateTestCase
from .personne import PersonneListTestCase
from .ouvre import OuvreDeleteTestCase
from .ouvre import OuvreUpdateTestCase
from .ouvre import OuvreDetailTestCase
from .ouvre import OuvreCreateTestCase
from .ouvre import OuvreListTestCase
from .exemplaire import ExemplaireDeleteTestCase
from .exemplaire import ExemplaireUpdateTestCase
from .exemplaire import ExemplaireDetailTestCase
from .exemplaire import ExemplaireCreateTestCase
from .exemplaire import ExemplaireListTestCase
from .batiment import BatimentDeleteTestCase
from .batiment import BatimentUpdateTestCase
from .batiment import BatimentDetailTestCase
from .batiment import BatimentCreateTestCase
from .batiment import BatimentListTestCase
from .barillet import BarilletDeleteTestCase
from .barillet import BarilletUpdateTestCase
from .barillet import BarilletDetailTestCase
from .barillet import BarilletCreateTestCase
from .barillet import BarilletListTestCase
from .archivage import ArchivageDeleteTestCase
from .archivage import ArchivageUpdateTestCase
from .archivage import ArchivageDetailTestCase
from .archivage import ArchivageCreateTestCase
from .archivage import ArchivageListTestCase
from .appartenir import AppartenirDeleteTestCase
from .appartenir import AppartenirUpdateTestCase
from .appartenir import AppartenirDetailTestCase
from .appartenir import AppartenirCreateTestCase
from .appartenir import AppartenirListTestCase
