from .utilisateur_delete_test import UtilisateurDeleteTestCase
from .utilisateur_update_test import UtilisateurUpdateTestCase
from .utilisateur_detail_test import UtilisateurDetailTestCase
from .utilisateur_create_test import UtilisateurCreateTestCase
from .utilisateur_list_test import UtilisateurListTestCase
