from .appartenir_delete_test import AppartenirDeleteTestCase
from .appartenir_update_test import AppartenirUpdateTestCase
from .appartenir_detail_test import AppartenirDetailTestCase
from .appartenir_create_test import AppartenirCreateTestCase
from .appartenir_list_test import AppartenirListTestCase
