from .variure import VariureDeleteView
from .variure import VariureUpdateView
from .variure import VariureDetailView
from .variure import VariureCreateView
from .variure import VariureListView
from .utilisateur import UtilisateurDeleteView
from .utilisateur import UtilisateurUpdateView
from .utilisateur import UtilisateurDetailView
from .utilisateur import UtilisateurCreateView
from .utilisateur import UtilisateurListView
from .type_exemplaire import TypeExemplaireDeleteView
from .type_exemplaire import TypeExemplaireUpdateView
from .type_exemplaire import TypeExemplaireDetailView
from .type_exemplaire import TypeExemplaireCreateView
from .type_exemplaire import TypeExemplaireListView
from .salle import SalleDeleteView
from .salle import SalleUpdateView
from .salle import SalleDetailView
from .salle import SalleCreateView
from .salle import SalleListView
from .roles import RolesDeleteView
from .roles import RolesUpdateView
from .roles import RolesDetailView
from .roles import RolesCreateView
from .roles import RolesListView
from .pouvoir import PouvoirDeleteView
from .pouvoir import PouvoirUpdateView
from .pouvoir import PouvoirDetailView
from .pouvoir import PouvoirCreateView
from .pouvoir import PouvoirListView
from .posseseur_de_c_lef import PosseseurDeCLefDeleteView
from .posseseur_de_c_lef import PosseseurDeCLefUpdateView
from .posseseur_de_c_lef import PosseseurDeCLefDetailView
from .posseseur_de_c_lef import PosseseurDeCLefCreateView
from .posseseur_de_c_lef import PosseseurDeCLefListView
from .porte import PorteDeleteView
from .porte import PorteUpdateView
from .porte import PorteDetailView
from .porte import PorteCreateView
from .porte import PorteListView
from .personne import PersonneDeleteView
from .personne import PersonneUpdateView
from .personne import PersonneDetailView
from .personne import PersonneCreateView
from .personne import PersonneListView
from .ouvre import OuvreDeleteView
from .ouvre import OuvreUpdateView
from .ouvre import OuvreDetailView
from .ouvre import OuvreCreateView
from .ouvre import OuvreListView
from .exemplaire import ExemplaireDeleteView
from .exemplaire import ExemplaireUpdateView
from .exemplaire import ExemplaireDetailView
from .exemplaire import ExemplaireCreateView
from .exemplaire import ExemplaireListView
from .batiment import BatimentDeleteView
from .batiment import BatimentUpdateView
from .batiment import BatimentDetailView
from .batiment import BatimentCreateView
from .batiment import BatimentListView
from .barillet import BarilletDeleteView
from .barillet import BarilletUpdateView
from .barillet import BarilletDetailView
from .barillet import BarilletCreateView
from .barillet import BarilletListView
from .archivage import ArchivageDeleteView
from .archivage import ArchivageUpdateView
from .archivage import ArchivageDetailView
from .archivage import ArchivageCreateView
from .archivage import ArchivageListView
from .appartenir import AppartenirDeleteView
from .appartenir import AppartenirUpdateView
from .appartenir import AppartenirDetailView
from .appartenir import AppartenirCreateView
from .appartenir import AppartenirListView
